/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as EditWizardRouteImport } from './routes/edit-wizard'
import { Route as CsvRouteImport } from './routes/csv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EditWizardRoute = EditWizardRouteImport.update({
  id: '/edit-wizard',
  path: '/edit-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvRoute = CsvRouteImport.update({
  id: '/csv',
  path: '/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csv': typeof CsvRoute
  '/edit-wizard': typeof EditWizardRoute
  '/pricing': typeof PricingRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csv': typeof CsvRoute
  '/edit-wizard': typeof EditWizardRoute
  '/pricing': typeof PricingRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csv': typeof CsvRoute
  '/edit-wizard': typeof EditWizardRoute
  '/pricing': typeof PricingRoute
  '/history/$id': typeof HistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/csv' | '/edit-wizard' | '/pricing' | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/csv' | '/edit-wizard' | '/pricing' | '/history/$id'
  id: '__root__' | '/' | '/csv' | '/edit-wizard' | '/pricing' | '/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsvRoute: typeof CsvRoute
  EditWizardRoute: typeof EditWizardRoute
  PricingRoute: typeof PricingRoute
  HistoryIdRoute: typeof HistoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-wizard': {
      id: '/edit-wizard'
      path: '/edit-wizard'
      fullPath: '/edit-wizard'
      preLoaderRoute: typeof EditWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv': {
      id: '/csv'
      path: '/csv'
      fullPath: '/csv'
      preLoaderRoute: typeof CsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsvRoute: CsvRoute,
  EditWizardRoute: EditWizardRoute,
  PricingRoute: PricingRoute,
  HistoryIdRoute: HistoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
